name:                tanks
version:             0.2.0.0
github:              "githubuser/tanks"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tanks#readme>

dependencies:
- base >= 4.7 && < 5
- GLUT >= 2.7 && < 3
- network >= 2.8 && < 3
- containers
- data-default >= 0.7 && < 1
- array
- primitive
- cereal
- bytestring
- binary
- sdl2
- sdl2-image
- text
- extra
- aeson
- mtl
- random
- utility-ht

library:
  source-dirs: src

executables:
  server-exe:
    main:                Main.hs
    source-dirs:         server
    ghc-options:
    - -threaded
      -fbreak-on-error
    dependencies:
    - tanks

  client-exe:
    main:                Main.hs
    source-dirs:         client
    ghc-options:
    - -threaded
    dependencies:
    - tanks


tests:
  tanks-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tanks
